# Generated by Django 3.2.11 on 2022-05-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changeManager', '0007_auto_20220519_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDigitizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitized_data', models.JSONField(blank=True, null=True)),
                ('last_digitized', models.DateTimeField(blank=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='digitizer', to='changeManager.boundarysource')),
            ],
        ),
    ]
