# Generated by Django 3.2.11 on 2022-05-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changeManager', '0006_auto_20220507_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_params', models.JSONField(blank=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='importer', to='changeManager.boundarysource')),
            ],
        ),
    ]
