# Generated by Django 3.2.4 on 2022-01-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.CharField(max_length=16)),
                ('date_end', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='changeManager.boundaryreference')),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='changeManager.boundaryreference')),
            ],
        ),
    ]
