# Generated by Django 3.2.4 on 2022-01-11 08:35

from django.db import migrations, models
import django.db.models.deletion
import djangowkb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('changeManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djangowkb.fields.GeometryField(editable=True, geom_type='GEOMETRY', srid=None)),
                ('source', models.CharField(max_length=100)),
                ('boundary_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='changeManager.boundaryreference')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='changeManager.event')),
            ],
        ),
    ]
