# Generated by Django 3.2.11 on 2022-01-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeManager', '0002_boundarysnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundaryname',
            name='boundary_ref',
        ),
        migrations.AddField(
            model_name='boundaryreference',
            name='names',
            field=models.ManyToManyField(related_name='boundary_refs', to='changeManager.BoundaryName'),
        ),
    ]
