# Generated by Django 3.2.11 on 2022-01-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeManager', '0003_auto_20220120_1138'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boundaryname',
            index=models.Index(fields=['name'], name='changeManag_name_462628_idx'),
        ),
    ]
