# Generated by Django 3.2.4 on 2022-03-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeManager', '0004_boundaryname_changemanag_name_462628_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TextSource', 'Text Source'), ('DataSource', 'Data Source'), ('MapSource', 'Map Source')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('citation', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boundarysnapshot',
            name='source',
        ),
        migrations.AddField(
            model_name='boundaryreference',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boundary_refs', to='changeManager.boundarysource'),
        ),
    ]
