# Generated by Django 3.2.11 on 2022-07-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeManager', '0008_auto_20220522_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='changeManager.boundarysource'),
        ),
    ]
